# Generated by Django 5.2.11 on 2026-06-05 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'segunda-feira'), (2, 'terca-feira'), (3, 'quarta-feira'), (4, 'quinta-feira'), (5, 'sexta-feira'), (6, 'sabado')])),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'ordering': ['dia_semana', 'horario_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planejada', 'planejada'), ('confirmada', 'confirmada'), ('cancelada', 'cancelada')], default='planejada', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='academico.disciplina')),
                ('periodo_letivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='academico.periodoletivo')),
            ],
            options={
                'verbose_name': 'alocacao',
                'verbose_name_plural': 'alocacoes',
                'ordering': ['-periodo_letivo__ano', '-periodo_letivo__semestre', 'horario__dia_semana', 'horario__horario_inicio'],
            },
        ),
    ]
