# Generated by Django 5.2.14 on 2026-06-02 17:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RecursoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'recurso de sala',
                'verbose_name_plural': 'recursos de sala',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=30)),
                ('carga_horaria_semanal', models.PositiveSmallIntegerField(help_text='quantidade de horas/aula por semana.', validators=[django.core.validators.MinValueValidator(1)])),
                ('periodo_recomendado', models.PositiveSmallIntegerField(blank=True, help_text='periodo/semestre ideal da grade, se existir.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas', to='alocacao.curso')),
                ('recursos_necessarios', models.ManyToManyField(blank=True, related_name='disciplinas', to='alocacao.recursosala')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ['curso__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'segunda-feira'), (2, 'terca-feira'), (3, 'quarta-feira'), (4, 'quinta-feira'), (5, 'sexta-feira'), (6, 'sabado')])),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'ordering': ['dia_semana', 'horario_inicio'],
                'indexes': [models.Index(fields=['dia_semana', 'horario_inicio'], name='horario_dia_inicio_idx')],
                'constraints': [models.UniqueConstraint(fields=('dia_semana', 'horario_inicio', 'horario_fim'), name='horario_faixa_unica'), models.CheckConstraint(condition=models.Q(('horario_fim__gt', models.F('horario_inicio'))), name='horario_fim_maior_inicio')],
            },
        ),
        migrations.CreateModel(
            name='PeriodoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ano', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('semestre', models.PositiveSmallIntegerField(help_text='use 1 ou 2 para semestre regular.', validators=[django.core.validators.MinValueValidator(1)])),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'periodo letivo',
                'verbose_name_plural': 'periodos letivos',
                'ordering': ['-ano', '-semestre'],
                'indexes': [models.Index(fields=['ano', 'semestre'], name='periodo_letivo_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('semestre__in', [1, 2])), name='periodo_letivo_semestre_valido'), models.CheckConstraint(condition=models.Q(('data_fim__gt', models.F('data_inicio'))), name='periodo_letivo_datas_validas'), models.UniqueConstraint(fields=('ano', 'semestre'), name='periodo_letivo_unico')],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('especialidade', models.CharField(blank=True, max_length=120)),
                ('carga_horaria_maxima', models.PositiveSmallIntegerField(help_text='limite semanal de horas/aula do professor.', validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='professor_nome_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('tipo_sala', models.CharField(choices=[('comum', 'comum'), ('laboratorio', 'laboratorio'), ('auditorio', 'auditorio'), ('online', 'online')], default='comum', max_length=20)),
                ('capacidade_alunos', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('localizacao', models.CharField(blank=True, max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('recursos', models.ManyToManyField(blank=True, related_name='salas', to='alocacao.recursosala')),
            ],
            options={
                'verbose_name': 'sala',
                'verbose_name_plural': 'salas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80)),
                ('turno', models.CharField(choices=[('matutino', 'matutino'), ('vespertino', 'vespertino'), ('noturno', 'noturno'), ('integral', 'integral')], max_length=20)),
                ('numero_alunos', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='alocacao.curso')),
                ('periodo_letivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='alocacao.periodoletivo')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ['-periodo_letivo__ano', '-periodo_letivo__semestre', 'curso__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('planejada', 'planejada'), ('confirmada', 'confirmada'), ('cancelada', 'cancelada')], default='planejada', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='alocacao.disciplina')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='alocacao.horario')),
                ('periodo_letivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='alocacao.periodoletivo')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='alocacao.professor')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='alocacao.sala')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='alocacao.turma')),
            ],
            options={
                'verbose_name': 'alocacao',
                'verbose_name_plural': 'alocacoes',
                'ordering': ['-periodo_letivo__ano', '-periodo_letivo__semestre', 'horario__dia_semana', 'horario__horario_inicio', 'sala__nome'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadeProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('observacao', models.CharField(blank=True, max_length=160)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_professores', to='alocacao.horario')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='alocacao.professor')),
            ],
            options={
                'verbose_name': 'disponibilidade do professor',
                'verbose_name_plural': 'disponibilidades dos professores',
                'ordering': ['professor__nome', 'horario__dia_semana', 'horario__horario_inicio'],
                'constraints': [models.UniqueConstraint(fields=('professor', 'horario'), name='disponibilidade_unica_por_professor_horario')],
            },
        ),
        migrations.AddIndex(
            model_name='disciplina',
            index=models.Index(fields=['codigo'], name='disciplina_codigo_idx'),
        ),
        migrations.AddConstraint(
            model_name='disciplina',
            constraint=models.UniqueConstraint(fields=('curso', 'codigo'), name='disciplina_codigo_unico_por_curso'),
        ),
        migrations.AddConstraint(
            model_name='disciplina',
            constraint=models.UniqueConstraint(fields=('curso', 'nome'), name='disciplina_nome_unico_por_curso'),
        ),
        migrations.AddIndex(
            model_name='sala',
            index=models.Index(fields=['tipo_sala'], name='sala_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='sala',
            index=models.Index(fields=['capacidade_alunos'], name='sala_capacidade_idx'),
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['periodo_letivo'], name='turma_periodo_idx'),
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['curso', 'periodo_letivo'], name='turma_curso_periodo_idx'),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('curso', 'periodo_letivo', 'nome'), name='turma_unica_por_periodo'),
        ),
        migrations.AddIndex(
            model_name='alocacao',
            index=models.Index(fields=['periodo_letivo', 'status'], name='aloc_periodo_status_idx'),
        ),
        migrations.AddIndex(
            model_name='alocacao',
            index=models.Index(fields=['periodo_letivo', 'sala', 'horario'], name='aloc_sala_horario_idx'),
        ),
        migrations.AddIndex(
            model_name='alocacao',
            index=models.Index(fields=['periodo_letivo', 'professor', 'horario'], name='aloc_prof_horario_idx'),
        ),
        migrations.AddIndex(
            model_name='alocacao',
            index=models.Index(fields=['periodo_letivo', 'turma', 'horario'], name='aloc_turma_horario_idx'),
        ),
        migrations.AddConstraint(
            model_name='alocacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['planejada', 'confirmada'])), fields=('periodo_letivo', 'sala', 'horario'), name='aloc_sala_horario_sem_conflito'),
        ),
        migrations.AddConstraint(
            model_name='alocacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['planejada', 'confirmada'])), fields=('periodo_letivo', 'professor', 'horario'), name='aloc_prof_horario_sem_conflito'),
        ),
        migrations.AddConstraint(
            model_name='alocacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['planejada', 'confirmada'])), fields=('periodo_letivo', 'turma', 'horario'), name='aloc_turma_horario_sem_conflito'),
        ),
    ]
