# Generated by Django 5.2.11 on 2026-06-05 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alocacao', '0001_initial'),
        ('infraestrutura', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacao',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='pessoas.professor'),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='infraestrutura.sala'),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='pessoas.turma'),
        ),
        migrations.AddIndex(
            model_name='horario',
            index=models.Index(fields=['dia_semana', 'horario_inicio'], name='horario_dia_inicio_idx'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('dia_semana', 'horario_inicio', 'horario_fim'), name='horario_faixa_unica'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.CheckConstraint(condition=models.Q(('horario_fim__gt', models.F('horario_inicio'))), name='horario_fim_maior_inicio'),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='alocacao.horario'),
        ),
        migrations.AddIndex(
            model_name='alocacao',
            index=models.Index(fields=['periodo_letivo', 'status'], name='aloc_periodo_status_idx'),
        ),
        migrations.AddIndex(
            model_name='alocacao',
            index=models.Index(fields=['periodo_letivo', 'sala', 'horario'], name='aloc_sala_horario_idx'),
        ),
        migrations.AddIndex(
            model_name='alocacao',
            index=models.Index(fields=['periodo_letivo', 'professor', 'horario'], name='aloc_prof_horario_idx'),
        ),
        migrations.AddIndex(
            model_name='alocacao',
            index=models.Index(fields=['periodo_letivo', 'turma', 'horario'], name='aloc_turma_horario_idx'),
        ),
        migrations.AddConstraint(
            model_name='alocacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['planejada', 'confirmada'])), fields=('periodo_letivo', 'sala', 'horario'), name='aloc_sala_horario_sem_conflito'),
        ),
        migrations.AddConstraint(
            model_name='alocacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['planejada', 'confirmada'])), fields=('periodo_letivo', 'professor', 'horario'), name='aloc_prof_horario_sem_conflito'),
        ),
        migrations.AddConstraint(
            model_name='alocacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['planejada', 'confirmada'])), fields=('periodo_letivo', 'turma', 'horario'), name='aloc_turma_horario_sem_conflito'),
        ),
    ]
