# Generated by Django 5.2.14 on 2026-07-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alocacao', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado')], max_length=10),
        ),
    ]
