# Generated by Django 6.0.6 on 2026-07-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alocacao', '0003_alter_horario_dia_semana'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['dia_semana', 'horario_inicio'], 'verbose_name': 'horário', 'verbose_name_plural': 'horários'},
        ),
        migrations.RemoveConstraint(
            model_name='horario',
            name='horario_fim_maior_inicio',
        ),
        migrations.RemoveIndex(
            model_name='horario',
            name='horario_dia_inicio_idx',
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.CharField(choices=[('1', 'Segunda-feira'), ('2', 'Terça-feira'), ('3', 'Quarta-feira'), ('4', 'Quinta-feira'), ('5', 'Sexta-feira'), ('6', 'Sábado')], max_length=1),
        ),
    ]
