# Generated by Django 5.2.11 on 2026-06-05 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'recurso de sala',
                'verbose_name_plural': 'recursos de sala',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('tipo_sala', models.CharField(choices=[('comum', 'comum'), ('laboratorio', 'laboratorio'), ('auditorio', 'auditorio'), ('online', 'online')], default='comum', max_length=20)),
                ('capacidade_alunos', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('localizacao', models.CharField(blank=True, max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('recursos', models.ManyToManyField(blank=True, related_name='salas', to='infraestrutura.recursosala')),
            ],
            options={
                'verbose_name': 'sala',
                'verbose_name_plural': 'salas',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['tipo_sala'], name='sala_tipo_idx'), models.Index(fields=['capacidade_alunos'], name='sala_capacidade_idx')],
            },
        ),
    ]
