# Generated by Django 5.2.11 on 2026-06-05 22:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infraestrutura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ano', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('semestre', models.PositiveSmallIntegerField(help_text='use 1 ou 2 para semestre regular.', validators=[django.core.validators.MinValueValidator(1)])),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'periodo letivo',
                'verbose_name_plural': 'periodos letivos',
                'ordering': ['-ano', '-semestre'],
                'indexes': [models.Index(fields=['ano', 'semestre'], name='periodo_letivo_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('semestre__in', [1, 2])), name='periodo_letivo_semestre_valido'), models.CheckConstraint(condition=models.Q(('data_fim__gt', models.F('data_inicio'))), name='periodo_letivo_datas_validas'), models.UniqueConstraint(fields=('ano', 'semestre'), name='periodo_letivo_unico')],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=30)),
                ('carga_horaria_semanal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('periodo_recomendado', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas', to='academico.curso')),
                ('recursos_necessarios', models.ManyToManyField(blank=True, related_name='disciplinas', to='infraestrutura.recursosala')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ['curso__nome', 'nome'],
                'indexes': [models.Index(fields=['codigo'], name='disciplina_codigo_idx')],
                'constraints': [models.UniqueConstraint(fields=('curso', 'codigo'), name='disciplina_codigo_unico_por_curso'), models.UniqueConstraint(fields=('curso', 'nome'), name='disciplina_nome_unico_por_curso')],
            },
        ),
    ]
