# Generated by Django 5.2.11 on 2026-06-05 22:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('alocacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('especialidade', models.CharField(blank=True, max_length=120)),
                ('carga_horaria_maxima', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='professor_nome_idx')],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadeProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponivel', models.BooleanField(default=True)),
                ('observacao', models.CharField(blank=True, max_length=160)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_professores', to='alocacao.horario')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='pessoas.professor')),
            ],
            options={
                'verbose_name': 'disponibilidade do professor',
                'verbose_name_plural': 'disponibilidades dos professores',
                'ordering': ['professor__nome', 'horario__dia_semana'],
                'constraints': [models.UniqueConstraint(fields=('professor', 'horario'), name='disponibilidade_unica_por_professor_horario')],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('turno', models.CharField(choices=[('matutino', 'matutino'), ('vespertino', 'vespertino'), ('noturno', 'noturno'), ('integral', 'integral')], max_length=20)),
                ('numero_alunos', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='academico.curso')),
                ('periodo_letivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='academico.periodoletivo')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ['-periodo_letivo__ano', '-periodo_letivo__semestre', 'nome'],
                'indexes': [models.Index(fields=['periodo_letivo'], name='turma_periodo_idx'), models.Index(fields=['curso', 'periodo_letivo'], name='turma_curso_periodo_idx')],
                'constraints': [models.UniqueConstraint(fields=('curso', 'periodo_letivo', 'nome'), name='turma_unica_por_periodo')],
            },
        ),
    ]
